### ISSUE TITLE
Cannot Install Modules

### ISSUE THREAD

**Issue by mehebub648** [doingthisalright/chatgpt-langchain-qna-on-your-docs#1]
While
`npm i`

This happens

> npm ERR! code 1
> npm ERR! path <path>
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.3.1
> npm ERR! gyp info using node@18.13.0 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.11.3 found at "C:\Users\MehebubMukut\AppData\Local\Programs\Python\Python311\python.exe"
> npm ERR! gyp ERR! find VS 
> npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
> npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> npm ERR! gyp ERR! find VS checking VS2022 (17.5.33627.172) found at:
> npm ERR! gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
> npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
> npm ERR! gyp ERR! find VS - missing any VC++ toolset
> npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
> npm ERR! gyp ERR! find VS looking for Visual Studio 2015
> npm ERR! gyp ERR! find VS - not found
> npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
> npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
> npm ERR! gyp ERR! find VS For more information consult the documentation at:
> npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
> npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\MehebubMukut\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)   
> npm ERR! gyp ERR! stack     at C:\Users\MehebubMukut\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
> npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\MehebubMukut\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
> npm ERR! gyp ERR! stack     at C:\Users\MehebubMukut\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
> npm ERR! gyp ERR! stack     at C:\Users\MehebubMukut\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
> npm ERR! gyp ERR! stack     at C:\Users\MehebubMukut\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
> npm ERR! gyp ERR! stack     at C:\Users\MehebubMukut\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
> npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
> npm ERR! gyp ERR! System Windows_NT 10.0.22621
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MehebubMukut\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd D:\Node\LangChainNew\YouTube101\backend\node_modules\hnswlib-node
> npm ERR! gyp ERR! node -v v18.13.0
> npm ERR! gyp ERR! node-gyp -v v9.3.1
> npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\MehebubMukut\AppData\Local\npm-cache\_logs\2023-05-04T17_17_26_221Z-debug-0.log
> 
![image](https://user-images.githubusercontent.com/119291101/236281411-a3de241f-722a-4375-b976-d2d139917a1c.png)

**Comment by doingthisalright** [comment]
Hello! Are you trying to use the terminal in VS Code?
Based on this error in the stack trace "Could not find any Visual Studio installation to use", it seems like a setup issue.

Also, it looks like you are on Windows. So can you try to run `npm i` on powershell, instead of using VS Code's Terminal?

**Comment by ccascio** [comment]
Hi, have exactly the same issue as above:
I tried to run "npm i", in the Terminal, in VS Code and in CMD, after deleting the node_modules and the package_lock.json but still the same error occurs after about npm runs. 
Do you know why it looks for VS? I have never installed it on this laptop.

**Comment by ccascio** [comment]
ok, I fixed this by doing the installation suggested here https://github.com/nodejs/node-gyp#on-windows

**Comment by doingthisalright** [comment]
Great! Thank you so much for sharing @ccascio. I really appreciate it.
If it interests you, please feel free to make a pull request with updates to the README.

@mehebub648 , I hope @ccascio's suggestion works for you as well. Feel free to re-open this issue if you need more help on this.
